/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddDoorInput {
  'heightEntered' : number,
  'heightRounded' : bigint,
  'widthEntered' : number,
  'coatingType' : CoatingType,
  'widthRounded' : bigint,
}
export type CoatingType = { 'doubleSagwan' : null } |
  { 'double' : null } |
  { 'laminate' : null } |
  { 'single' : null };
export interface ComputeTotals {
  'singleCoating' : number,
  'doubleSagwan' : number,
  'laminate' : number,
  'doubleCoating' : number,
  'grandTotal' : number,
}
export interface CreateDoorType { 'createdType' : DoorEntry }
export interface DoorEntry {
  'id' : bigint,
  'squareFeet' : number,
  'heightEntered' : number,
  'heightRounded' : bigint,
  'widthEntered' : number,
  'coatingType' : CoatingType,
  'widthRounded' : bigint,
}
export interface _SERVICE {
  'addDoor' : ActorMethod<[AddDoorInput], CreateDoorType>,
  'deleteDoor' : ActorMethod<[bigint], undefined>,
  'getAll' : ActorMethod<[], Array<DoorEntry>>,
  'getEntry' : ActorMethod<[bigint], DoorEntry>,
  'getTotals' : ActorMethod<[], ComputeTotals>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];