/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CoatingType = IDL.Variant({
  'doubleSagwan' : IDL.Null,
  'double' : IDL.Null,
  'laminate' : IDL.Null,
  'single' : IDL.Null,
});
export const AddDoorInput = IDL.Record({
  'heightEntered' : IDL.Float64,
  'heightRounded' : IDL.Nat,
  'widthEntered' : IDL.Float64,
  'coatingType' : CoatingType,
  'widthRounded' : IDL.Nat,
});
export const DoorEntry = IDL.Record({
  'id' : IDL.Nat,
  'squareFeet' : IDL.Float64,
  'heightEntered' : IDL.Float64,
  'heightRounded' : IDL.Nat,
  'widthEntered' : IDL.Float64,
  'coatingType' : CoatingType,
  'widthRounded' : IDL.Nat,
});
export const CreateDoorType = IDL.Record({ 'createdType' : DoorEntry });
export const ComputeTotals = IDL.Record({
  'singleCoating' : IDL.Float64,
  'doubleSagwan' : IDL.Float64,
  'laminate' : IDL.Float64,
  'doubleCoating' : IDL.Float64,
  'grandTotal' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addDoor' : IDL.Func([AddDoorInput], [CreateDoorType], []),
  'deleteDoor' : IDL.Func([IDL.Nat], [], []),
  'getAll' : IDL.Func([], [IDL.Vec(DoorEntry)], ['query']),
  'getTotals' : IDL.Func([], [ComputeTotals], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CoatingType = IDL.Variant({
    'doubleSagwan' : IDL.Null,
    'double' : IDL.Null,
    'laminate' : IDL.Null,
    'single' : IDL.Null,
  });
  const AddDoorInput = IDL.Record({
    'heightEntered' : IDL.Float64,
    'heightRounded' : IDL.Nat,
    'widthEntered' : IDL.Float64,
    'coatingType' : CoatingType,
    'widthRounded' : IDL.Nat,
  });
  const DoorEntry = IDL.Record({
    'id' : IDL.Nat,
    'squareFeet' : IDL.Float64,
    'heightEntered' : IDL.Float64,
    'heightRounded' : IDL.Nat,
    'widthEntered' : IDL.Float64,
    'coatingType' : CoatingType,
    'widthRounded' : IDL.Nat,
  });
  const CreateDoorType = IDL.Record({ 'createdType' : DoorEntry });
  const ComputeTotals = IDL.Record({
    'singleCoating' : IDL.Float64,
    'doubleSagwan' : IDL.Float64,
    'laminate' : IDL.Float64,
    'doubleCoating' : IDL.Float64,
    'grandTotal' : IDL.Float64,
  });
  
  return IDL.Service({
    'addDoor' : IDL.Func([AddDoorInput], [CreateDoorType], []),
    'deleteDoor' : IDL.Func([IDL.Nat], [], []),
    'getAll' : IDL.Func([], [IDL.Vec(DoorEntry)], ['query']),
    'getTotals' : IDL.Func([], [ComputeTotals], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };