/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DoorEntry = IDL.Record({
  'id' : IDL.Nat,
  'height' : IDL.Float64,
  'rate' : IDL.Float64,
  'squareFeet' : IDL.Float64,
  'roundedHeight' : IDL.Nat,
  'roundedWidth' : IDL.Nat,
  'width' : IDL.Float64,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addDoorEntry' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Opt(IDL.Float64)],
      [DoorEntry],
      [],
    ),
  'deleteEntry' : IDL.Func([IDL.Nat], [], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(DoorEntry)], ['query']),
  'getGrandTotalAmount' : IDL.Func([], [IDL.Nat], ['query']),
  'getGrandTotalSquareFeet' : IDL.Func([], [IDL.Float64], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DoorEntry = IDL.Record({
    'id' : IDL.Nat,
    'height' : IDL.Float64,
    'rate' : IDL.Float64,
    'squareFeet' : IDL.Float64,
    'roundedHeight' : IDL.Nat,
    'roundedWidth' : IDL.Nat,
    'width' : IDL.Float64,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addDoorEntry' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Opt(IDL.Float64)],
        [DoorEntry],
        [],
      ),
    'deleteEntry' : IDL.Func([IDL.Nat], [], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(DoorEntry)], ['query']),
    'getGrandTotalAmount' : IDL.Func([], [IDL.Nat], ['query']),
    'getGrandTotalSquareFeet' : IDL.Func([], [IDL.Float64], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };