/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddDoorInput {
  'height' : number,
  'width' : number,
  'coatings' : CoatingType,
}
export interface AddDoorOutput { 'createdType' : DoorType }
export interface CoatingType {
  'singleCoating' : boolean,
  'doubleSagwan' : boolean,
  'laminate' : boolean,
  'doubleCoating' : boolean,
}
export interface DoorType {
  'id' : bigint,
  'height' : number,
  'squareFeet' : number,
  'roundedHeight' : bigint,
  'roundedWidth' : bigint,
  'width' : number,
  'coatings' : CoatingType,
}
export interface _SERVICE {
  'addDoor' : ActorMethod<[AddDoorInput], AddDoorOutput>,
  'calculateCoatingAmounts' : ActorMethod<
    [],
    {
      'doubleCoatingAmount' : number,
      'laminateAmount' : number,
      'singleCoatingAmount' : number,
      'doubleSagwanAmount' : number,
    }
  >,
  'deleteType' : ActorMethod<[bigint], undefined>,
  'getAllTypes' : ActorMethod<[], Array<DoorType>>,
  'getCoatingTotals' : ActorMethod<
    [],
    {
      'singleCoating' : number,
      'doubleSagwan' : number,
      'laminate' : number,
      'doubleCoating' : number,
    }
  >,
  'getTotalSquareFeet' : ActorMethod<[], number>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];