/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CoatingType {
    singleCoating: boolean;
    doubleSagwan: boolean;
    laminate: boolean;
    doubleCoating: boolean;
}
export interface AddDoorOutput {
    createdType: DoorType;
}
export interface AddDoorInput {
    roundedHeight: bigint;
    roundedWidth: bigint;
    enteredWidth: string;
    enteredHeight: string;
    coatings: CoatingType;
}
export interface DoorType {
    id: bigint;
    squareFeet: number;
    roundedHeight: bigint;
    roundedWidth: bigint;
    enteredWidth: string;
    enteredHeight: string;
    coatings: CoatingType;
}
export interface backendInterface {
    addDoor(input: AddDoorInput): Promise<AddDoorOutput>;
    calculateCoatingAmounts(): Promise<{
        doubleCoatingAmount: number;
        laminateAmount: number;
        singleCoatingAmount: number;
        doubleSagwanAmount: number;
    }>;
    deleteType(id: bigint): Promise<void>;
    getAllTypes(): Promise<Array<DoorType>>;
    getCoatingTotals(): Promise<{
        singleCoating: number;
        doubleSagwan: number;
        laminate: number;
        doubleCoating: number;
    }>;
    getTotalSquareFeet(): Promise<number>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDoor(arg0: AddDoorInput): Promise<AddDoorOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.addDoor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDoor(arg0);
            return result;
        }
    }
    async calculateCoatingAmounts(): Promise<{
        doubleCoatingAmount: number;
        laminateAmount: number;
        singleCoatingAmount: number;
        doubleSagwanAmount: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateCoatingAmounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateCoatingAmounts();
            return result;
        }
    }
    async deleteType(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteType(arg0);
            return result;
        }
    }
    async getAllTypes(): Promise<Array<DoorType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTypes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTypes();
            return result;
        }
    }
    async getCoatingTotals(): Promise<{
        singleCoating: number;
        doubleSagwan: number;
        laminate: number;
        doubleCoating: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoatingTotals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoatingTotals();
            return result;
        }
    }
    async getTotalSquareFeet(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalSquareFeet();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalSquareFeet();
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
