/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateDoorType {
    createdType: DoorEntry;
}
export interface ComputeTotals {
    singleCoating: number;
    doubleSagwan: number;
    laminate: number;
    doubleCoating: number;
    grandTotal: number;
}
export interface AddDoorInput {
    heightEntered: number;
    heightRounded: bigint;
    widthEntered: number;
    coatingType: CoatingType;
    widthRounded: bigint;
}
export interface DoorEntry {
    id: bigint;
    squareFeet: number;
    heightEntered: number;
    heightRounded: bigint;
    widthEntered: number;
    coatingType: CoatingType;
    widthRounded: bigint;
}
export enum CoatingType {
    doubleSagwan = "doubleSagwan",
    double_ = "double",
    laminate = "laminate",
    single = "single"
}
export interface backendInterface {
    addDoor(input: AddDoorInput): Promise<CreateDoorType>;
    deleteDoor(id: bigint): Promise<void>;
    getAll(): Promise<Array<DoorEntry>>;
    getEntry(id: bigint): Promise<DoorEntry>;
    getTotals(): Promise<ComputeTotals>;
}
import type { AddDoorInput as _AddDoorInput, CoatingType as _CoatingType, CreateDoorType as _CreateDoorType, DoorEntry as _DoorEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDoor(arg0: AddDoorInput): Promise<CreateDoorType> {
        if (this.processError) {
            try {
                const result = await this.actor.addDoor(to_candid_AddDoorInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CreateDoorType_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDoor(to_candid_AddDoorInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CreateDoorType_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDoor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDoor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDoor(arg0);
            return result;
        }
    }
    async getAll(): Promise<Array<DoorEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAll();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAll();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEntry(arg0: bigint): Promise<DoorEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntry(arg0);
                return from_candid_DoorEntry_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntry(arg0);
            return from_candid_DoorEntry_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotals(): Promise<ComputeTotals> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotals();
            return result;
        }
    }
}
function from_candid_CoatingType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoatingType): CoatingType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_CreateDoorType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateDoorType): CreateDoorType {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_DoorEntry_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DoorEntry): DoorEntry {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdType: _DoorEntry;
}): {
    createdType: DoorEntry;
} {
    return {
        createdType: from_candid_DoorEntry_n7(_uploadFile, _downloadFile, value.createdType)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    squareFeet: number;
    heightEntered: number;
    heightRounded: bigint;
    widthEntered: number;
    coatingType: _CoatingType;
    widthRounded: bigint;
}): {
    id: bigint;
    squareFeet: number;
    heightEntered: number;
    heightRounded: bigint;
    widthEntered: number;
    coatingType: CoatingType;
    widthRounded: bigint;
} {
    return {
        id: value.id,
        squareFeet: value.squareFeet,
        heightEntered: value.heightEntered,
        heightRounded: value.heightRounded,
        widthEntered: value.widthEntered,
        coatingType: from_candid_CoatingType_n9(_uploadFile, _downloadFile, value.coatingType),
        widthRounded: value.widthRounded
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    doubleSagwan: null;
} | {
    double: null;
} | {
    laminate: null;
} | {
    single: null;
}): CoatingType {
    return "doubleSagwan" in value ? CoatingType.doubleSagwan : "double" in value ? CoatingType.double : "laminate" in value ? CoatingType.laminate : "single" in value ? CoatingType.single : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DoorEntry>): Array<DoorEntry> {
    return value.map((x)=>from_candid_DoorEntry_n7(_uploadFile, _downloadFile, x));
}
function to_candid_AddDoorInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddDoorInput): _AddDoorInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CoatingType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoatingType): _CoatingType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heightEntered: number;
    heightRounded: bigint;
    widthEntered: number;
    coatingType: CoatingType;
    widthRounded: bigint;
}): {
    heightEntered: number;
    heightRounded: bigint;
    widthEntered: number;
    coatingType: _CoatingType;
    widthRounded: bigint;
} {
    return {
        heightEntered: value.heightEntered,
        heightRounded: value.heightRounded,
        widthEntered: value.widthEntered,
        coatingType: to_candid_CoatingType_n3(_uploadFile, _downloadFile, value.coatingType),
        widthRounded: value.widthRounded
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoatingType): {
    doubleSagwan: null;
} | {
    double: null;
} | {
    laminate: null;
} | {
    single: null;
} {
    return value == CoatingType.doubleSagwan ? {
        doubleSagwan: null
    } : value == CoatingType.double ? {
        double_: null
    } : value == CoatingType.laminate ? {
        laminate: null
    } : value == CoatingType.single ? {
        single: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
